# Default values for container-nanny.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: allantargino/container-nanny
  tag: latest
  pullPolicy: Always

settings:
  QUEUE_CONNECTION_STRING:
  QUEUE_NAME:
  K8S_NAMESPACE: default
  K8S_CR_SECRET:
  JOB_CONTAINER_NAME: nanny-job
  JOB_CONTAINER_IMAGE:
  JOB_CONFIGMAP_NAME:
  JOB_MAX_POD : 10
  JOB_CPU_REQUEST : 250m
  JOB_CPU_LIMIT : 500m
  JOB_MEM_REQUEST : 50Mi
  JOB_MEM_LIMIT : 100Mi

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
